// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._CorvaxGoob.Traitor.HighRiskPinpointer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CorvaxGoob.Traitor.HighRiskPinpointer;

/// <summary>
/// Lets the user choose a fixed high-risk target or switch to exact DNA tracking in one compact window.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class HighRiskPinpointerWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;

    // DNA search is appended after every fixed target, so its selection ID follows the catalog indexes.
    private static int DnaSelectionId => HighRiskPinpointerTargetCatalog.Targets.Length;

    public event Action<int, string>? SearchSubmitted;
    public event Action<int>? SelectionChanged;

    public HighRiskPinpointerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        foreach (var target in HighRiskPinpointerTargetCatalog.Targets)
        {
            var name = target.Name is { } nameId
                ? Loc.GetString(nameId)
                : _prototypes.Index<EntityPrototype>(target.Prototypes[0]).Name;
            TargetSelector.AddItem(name);
        }

        TargetSelector.AddItem(Loc.GetString("high-risk-pinpointer-dna-button"), DnaSelectionId);
        SelectTarget(0);

        // DNA is generated from Latin nucleotide letters; accepting either case keeps manual input convenient.
        DnaInput.IsValid = text => text.All(char.IsAsciiLetter);

        TargetSelector.OnItemSelected += args =>
        {
            TargetSelector.SelectId(args.Id);
            DnaInput.Visible = args.Id == DnaSelectionId;
            SelectionChanged?.Invoke(args.Id);
        };
        SearchButton.OnPressed += _ => SubmitSearch();
        DnaInput.OnTextEntered += _ => SubmitSearch();
    }

    /// <summary>
    /// Restores the last selection after the pinpointer window is opened again.
    /// </summary>
    public void SelectTarget(int id)
    {
        if (!TargetSelector.TrySelectId(id))
            return;

        DnaInput.Visible = id == DnaSelectionId;
    }

    private void SubmitSearch()
    {
        if (TargetSelector.SelectedId == DnaSelectionId && string.IsNullOrWhiteSpace(DnaInput.Text))
            return;

        SearchSubmitted?.Invoke(TargetSelector.SelectedId, DnaInput.Text);
    }
}
