// SPDX-FileCopyrightText: 2021 20kdc <asdd2808@gmail.com>
// SPDX-FileCopyrightText: 2021 Metal Gear Sloth <metalgearsloth@gmail.com>
// SPDX-FileCopyrightText: 2021 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto <6766154+Zumorica@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Alex Evgrashin <aevgrashin@yandex.ru>
// SPDX-FileCopyrightText: 2022 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <Jezithyr.@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <Jezithyr@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <jmaster9999@gmail.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 wrexbe <wrexbe@protonmail.com>
// SPDX-FileCopyrightText: 2023 Ray <vigersray@gmail.com>
// SPDX-FileCopyrightText: 2023 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 deltanedas <@deltanedas:kde.org>
// SPDX-FileCopyrightText: 2024 Intoxicating-Innocence <188202277+Intoxicating-Innocence@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 MilenVolf <63782763+MilenVolf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 no <165581243+pissdemon@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics; // CorvaxGoob
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostRolesWindow : DefaultWindow
    {
        public event Action<GhostRoleInfo>? OnRoleRequestButtonClicked;
        public event Action<GhostRoleInfo>? OnRoleFollow;

        // CorvaxGoob Edit Start
        private readonly Dictionary<GhostRoleCategory, Collapsible> _categoryCollapsibleBoxes = new();
        private readonly Dictionary<(GhostRoleCategory category, string name, string description), Collapsible> _collapsibleBoxes = new();
        private readonly HashSet<GhostRoleCategory> _uncollapsedCategoryStates = new();
        private readonly HashSet<(GhostRoleCategory category, string name, string description)> _uncollapsedStates = new();
        private bool _hasSavedCategoryStates;
        private bool _hasSavedRoleStates;
        // CorvaxGoob End

        public GhostRolesWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void ClearEntries()
        {
            NoRolesMessage.Visible = true;
            EntryContainer.DisposeAllChildren();
            _categoryCollapsibleBoxes.Clear(); // CorvaxGoob
            _collapsibleBoxes.Clear();
            InvalidateRoleListLayout(); // CorvaxGoob
        }

        public void SaveCollapsibleBoxesStates()
        {
            // CorvaxGoob Edit Start
            _hasSavedCategoryStates = _categoryCollapsibleBoxes.Count > 0;
            _hasSavedRoleStates = _collapsibleBoxes.Count > 0;
            _uncollapsedCategoryStates.Clear();
            _uncollapsedStates.Clear();

            foreach (var (key, collapsible) in _categoryCollapsibleBoxes)
            {
                if (collapsible.BodyVisible)
                {
                    _uncollapsedCategoryStates.Add(key);
                }
            }
            // CorvaxGoob End

            foreach (var (key, collapsible) in _collapsibleBoxes)
            {
                if (collapsible.BodyVisible)
                {
                    _uncollapsedStates.Add(key);
                }
            }
        }

        public void RestoreCollapsibleBoxesStates()
        {
            // CorvaxGoob Start
            if (_hasSavedCategoryStates)
            {
                foreach (var (key, collapsible) in _categoryCollapsibleBoxes)
                {
                    collapsible.BodyVisible = _uncollapsedCategoryStates.Contains(key);
                    if (collapsible.Heading is CollapsibleHeading heading)
                        ApplyCategoryHeadingStyle(heading, key, collapsible.BodyVisible);
                }
            }

            if (!_hasSavedRoleStates)
                return;
            // CorvaxGoob End

            foreach (var (key, collapsible) in _collapsibleBoxes)
            {
                collapsible.BodyVisible = _uncollapsedStates.Contains(key);
            }
        }

        // CorvaxGoob Edit Start
        public void InvalidateRoleListLayout()
        {
            EntryContainer.InvalidateMeasure();
            RoleScroll.InvalidateMeasure();
            InvalidateMeasure();
        }

        public BoxContainer AddCategory(GhostRoleCategory category, int rolesCount)
        {
            NoRolesMessage.Visible = false;

            var heading = new CollapsibleHeading(Loc.GetString(GetCategoryLocId(category), ("rolesCount", rolesCount)));
            heading.AddStyleClass(ContainerButton.StyleClassButton);
            heading.Label.HorizontalAlignment = HAlignment.Center;
            heading.Label.HorizontalExpand = true;
            heading.Margin = new Thickness(10, 0, 10, 4);
            heading.OnToggled += args => ApplyCategoryHeadingStyle(heading, category, args.Pressed);

            var body = new CollapsibleBody
            {
                Margin = new Thickness(0, 8, 0, 0),
                HorizontalExpand = true,
            };

            var categoryContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            body.AddChild(categoryContainer);

            var collapsible = new Collapsible(heading, body)
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                BodyVisible = true,
                HorizontalExpand = true,
            };
            ApplyCategoryHeadingStyle(heading, category, collapsible.BodyVisible);

            var sectionStyle = GetCategoryPalette(category);
            var section = new PanelContainer
            {
                Margin = new Thickness(0, 0, 0, 12),
                HorizontalExpand = true,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = sectionStyle.Background,
                    BorderColor = sectionStyle.Border,
                    BorderThickness = new Thickness(1),
                    ContentMarginBottomOverride = 10,
                    ContentMarginLeftOverride = 10,
                    ContentMarginRightOverride = 10,
                    ContentMarginTopOverride = 10,
                },
            };

            section.AddChild(collapsible);
            EntryContainer.AddChild(section);
            _categoryCollapsibleBoxes.Add(category, collapsible);
            return categoryContainer;
        }
        // CorvaxGoob End

        public void AddEntry(
            BoxContainer entryContainer,
            GhostRoleCategory category,
            string name,
            string description,
            bool hasAccess,
            FormattedMessage? reason,
            bool highlighted,
            IEnumerable<GhostRoleInfo> roles,
            SpriteSystem spriteSystem) // CorvaxGoob Edit
        {
            var ghostRoleInfos = roles.ToList();
            var rolesCount = ghostRoleInfos.Count;

            var info = new GhostRoleInfoBox(name, description);
            var buttons = new GhostRoleButtonsBox(hasAccess, reason, ghostRoleInfos, spriteSystem);
            buttons.OnRoleSelected += OnRoleRequestButtonClicked;
            buttons.OnRoleFollow += OnRoleFollow;

            // CorvaxGoob Edit Start
            var roleContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            if (highlighted)
            {
                var highlightStyle = GetHighlightedEntryPalette(category);
                var highlightPanel = new PanelContainer
                {
                    Margin = new Thickness(2, 0, 2, 12),
                    HorizontalExpand = true,
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = highlightStyle.Background,
                        BorderColor = highlightStyle.Border,
                        BorderThickness = new Thickness(1),
                        ContentMarginBottomOverride = 8,
                        ContentMarginLeftOverride = 8,
                        ContentMarginRightOverride = 8,
                        ContentMarginTopOverride = 8,
                    },
                };

                highlightPanel.AddChild(roleContainer);
                entryContainer.AddChild(highlightPanel);
            }
            else
            {
                roleContainer.Margin = new Thickness(4, 0, 4, 12);
                entryContainer.AddChild(roleContainer);
            }

            roleContainer.AddChild(info);
            // CorvaxGoob End

            if (rolesCount > 1)
            {
                var buttonHeading = new CollapsibleHeading(Loc.GetString("ghost-roles-window-available-button", ("rolesCount", rolesCount)));

                buttonHeading.AddStyleClass(ContainerButton.StyleClassButton);
                buttonHeading.Label.HorizontalAlignment = HAlignment.Center;
                buttonHeading.Label.HorizontalExpand = true;
                buttonHeading.Margin = new Thickness(8, 2, 8, 4); // CorvaxGoob Edit

                var body = new CollapsibleBody
                {
                    // CorvaxGoob Edit Start
                    Margin = new Thickness(0, 6, 0, 0),
                    HorizontalExpand = true,
                    // CorvaxGoob End
                };

                // TODO: Add Requirements to this key when it'll be fixed and work as an equality key in GhostRolesEui
                var key = (category, name, description); // CorvaxGoob Edit

                var collapsible = new Collapsible(buttonHeading, body)
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    // CorvaxGoob Edit Start
                    Margin = new Thickness(0, 2, 0, 0),
                    HorizontalExpand = true,
                    // CorvaxGoob End
                };

                body.AddChild(buttons);

                roleContainer.AddChild(collapsible); // CorvaxGoob Edit
                _collapsibleBoxes.Add(key, collapsible);
            }
            else
            {
                roleContainer.AddChild(buttons); // CorvaxGoob Edit
            }
        }

        // CorvaxGoob Start
        private static string GetCategoryLocId(GhostRoleCategory category)
        {
            return category switch
            {
                GhostRoleCategory.Antagonist => "ghost-roles-window-category-antagonist",
                GhostRoleCategory.Other => "ghost-roles-window-category-other",
                _ => "ghost-roles-window-category-other",
            };
        }

        private static (Color Background, Color Border, Color ButtonCollapsed, Color ButtonActive) GetCategoryPalette(GhostRoleCategory category)
        {
            return category switch
            {
                GhostRoleCategory.Antagonist => (Color.FromHex("#2A1010CC"), Color.FromHex("#A84A4AFF"), Color.FromHex("#3A1717FF"), Color.FromHex("#A84A4AFF")),
                GhostRoleCategory.Other => (Color.FromHex("#202026CC"), Color.FromHex("#77778AFF"), Color.FromHex("#30303AFF"), Color.FromHex("#77778AFF")),
                _ => (Color.FromHex("#202026CC"), Color.FromHex("#77778AFF"), Color.FromHex("#30303AFF"), Color.FromHex("#77778AFF")),
            };
        }

        private static (Color Background, Color Border) GetHighlightedEntryPalette(GhostRoleCategory category)
        {
            return category switch
            {
                GhostRoleCategory.Antagonist => (Color.FromHex("#441818DD"), Color.FromHex("#D66A6AFF")),
                _ => (Color.FromHex("#343440DD"), Color.FromHex("#9999AEFF")),
            };
        }

        private static void ApplyCategoryHeadingStyle(CollapsibleHeading heading, GhostRoleCategory category, bool active)
        {
            var palette = GetCategoryPalette(category);
            heading.StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = active ? palette.ButtonActive : palette.ButtonCollapsed,
                BorderColor = palette.Border,
                BorderThickness = new Thickness(1),
                ContentMarginBottomOverride = 4,
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 4,
            };
        }
        // CorvaxGoob End
    }
}
